spring:
  profiles:
    include: secret
  application:
    name: CoMentor-BE
  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
logging:
    level:
        org.springframework.security: DEBUG


#springdoc:
#  swagger-ui:
#    persistAuthorization: true
